-- ============================================================
-- Cake Delight — Supabase schema
-- Run this in Supabase Studio → SQL Editor (or supabase db push)
-- Then: Authentication → Users → Add user:
--   email: admin@cakedelight.pk  ·  password: (your choice)
-- ============================================================

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  category text not null check (category in ('birthday','wedding','kids','anniversary','cupcakes')),
  description text not null,
  long_description text default '',
  price numeric not null check (price > 0),
  image text not null default '/img/cat-birthday.jpg',
  rating numeric default 4.8,
  reviews integer default 0,
  badge text default '',
  bestseller boolean default false,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists flavors (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  tag text default 'classic' check (tag in ('classic','premium','fruity')),
  active boolean default true
);

create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  location text default 'Sahiwal',
  text text not null,
  rating integer default 5 check (rating between 1 and 5),
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text unique,
  customer_name text not null,
  phone text not null,
  email text default '',
  address text not null,
  city text default 'Sahiwal',
  notes text default '',
  delivery_date text default '',
  delivery_slot text default 'anytime',
  subtotal numeric not null,
  delivery_fee numeric not null default 0,
  total numeric not null,
  payment_method text default 'cod',
  status text default 'pending' check (status in ('pending','confirmed','baking','out-for-delivery','delivered','cancelled')),
  created_at timestamptz default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint,
  name text not null,
  image text default '',
  unit_price numeric not null,
  qty integer not null default 1,
  size text default '2 lb',
  flavor text default '',
  message text default ''
);

create table if not exists custom_orders (
  id bigint generated by default as identity primary key,
  ref_no text unique,
  name text not null,
  phone text not null,
  email text default '',
  occasion text not null,
  design text not null,
  flavor text not null,
  size text not null,
  servings integer default 12,
  delivery_date text default '',
  message text default '',
  budget text default '',
  status text default 'new' check (status in ('new','discussing','quoted','confirmed','completed','cancelled')),
  admin_notes text default '',
  created_at timestamptz default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text default '',
  phone text default '',
  subject text default 'General',
  message text not null,
  is_read boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_products_category on products(category);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_order_items_order on order_items(order_id);

-- Row Level Security: all access happens server-side through the Next.js API
-- (service role key bypasses RLS), so we simply enable RLS with no public policies.
alter table products enable row level security;
alter table flavors enable row level security;
alter table testimonials enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table custom_orders enable row level security;
alter table messages enable row level security;

-- -------------------------- seed data --------------------------
insert into products (name, slug, category, description, long_description, price, image, rating, reviews, badge, bestseller) values
('Chocolate Truffle Cake','chocolate-truffle-cake','birthday','Rich chocolate layers with silky truffle ganache and chocolate curls.','Our signature Chocolate Truffle Cake layers moist chocolate sponge with silky dark truffle ganache, finished with hand-rolled chocolate curls and a dusting of premium cocoa. Made fresh to order with imported Belgian chocolate.',2500,'/img/prod-chocolate-truffle.jpg',4.9,128,'Best Seller',true),
('Red Velvet Cake','red-velvet-cake','anniversary','Classic red velvet with smooth cream cheese frosting.','A timeless classic — deep red velvet sponge with buttermilk tenderness, layered with silky cream cheese frosting and coated in red velvet crumbs, topped with fresh raspberries.',2800,'/img/prod-red-velvet.jpg',4.8,96,'',true),
('Unicorn Kids Cake','unicorn-kids-cake','kids','Magical pastel mane, golden horn and glitter stars.','Every child''s dream cake! A magical unicorn with a pastel buttercream mane in pink, lavender and mint, a golden horn and edible glitter stars. Funfetti sponge inside makes every slice a party.',3000,'/img/prod-unicorn.jpg',4.9,74,'Kids Favorite',true),
('Lotus Biscoff Cake','lotus-biscoff-cake','birthday','Caramel drip, Lotus biscuits and biscoff spread.','The internet''s favorite flavor — soft sponge layered with velvety Lotus Biscoff spread, a glossy caramel drip, crushed biscuit crumbs and whole Lotus biscuits on top.',2700,'/img/prod-biscoff.jpg',4.8,61,'Trending',true),
('Floral Wedding Cake','floral-wedding-cake','wedding','Three ivory tiers with blush roses and pearl details.','A show-stopping three-tier wedding cake in smooth ivory buttercream with hand-piped pearl details, blush garden roses and cascading greenery. Fully customizable to your wedding palette.',6500,'/img/cat-wedding.jpg',5.0,52,'Premium',true),
('Heart Anniversary Cake','heart-anniversary-cake','anniversary','Heart-shaped red velvet with rose petals.','Celebrate love with sweetness — a heart-shaped red velvet cake with cream cheese frosting, fresh raspberries, dried rose petals and an elegant gold topper.',3200,'/img/cat-anniversary.jpg',4.9,45,'',false),
('Celebration Cupcakes (Box of 6)','celebration-cupcakes','cupcakes','Swirls of pink buttercream with gold sprinkles.','Little treats, big happiness! A box of six gourmet cupcakes with tall swirls of blush-pink buttercream, gold sprinkles and rose petals.',1200,'/img/cat-cupcakes.jpg',4.8,38,'',false),
('Rainbow Party Cake','rainbow-party-cake','kids','Colorful Funfetti sponge with pastel buttercream.','A party in every slice! Layers of colorful funfetti sponge under pastel pink buttercream with rainbow sprinkles.',2800,'/img/cat-kids.jpg',4.7,29,'',false);

insert into flavors (name, description, tag) values
('Chocolate Truffle','Belgian chocolate sponge with dark truffle ganache','classic'),
('Red Velvet','Classic buttermilk red velvet with cream cheese frosting','classic'),
('Vanilla Bean','Madagascar vanilla sponge with silky buttercream','classic'),
('Lotus Biscoff','Spiced biscoff spread with caramel drip','premium'),
('Pistachio Rose','Roasted pistachio sponge with rose cream','premium'),
('Chocolate Fudge','Double chocolate fudge with ganache layers','classic'),
('Funfetti','Vanilla sponge loaded with rainbow sprinkles','classic'),
('Strawberry Cream','Fresh strawberry compote with whipped cream','fruity'),
('Mango Delight','Seasonal mango chunks with mango mousse','fruity'),
('Butterscotch','Caramel butterscotch with praline crunch','premium'),
('Caramel Coffee','Espresso sponge with salted caramel','premium'),
('Coconut Dream','Coconut sponge with mascarpone cream','fruity');

insert into testimonials (name, location, text, rating) values
('Usman Ali','Sahiwal','From ordering to delivery, everything was smooth. The cake was fresh and delicious and the service was even better. Highly recommended!',5),
('Ayesha Malik','Sahiwal','The custom cake for my daughter''s birthday was exactly what I imagined — beautiful design and amazing taste. Will order again for sure!',5),
('Sara & Bilal','Sahiwal','Our anniversary cake was a big hit! So creative, delivered on time and in perfect condition. Cake Delight never disappoints.',5);
